global:
  scrape_interval: 5s

  evaluation_interval: 5s

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped>
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seco>
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
       - targets: ['netdata:19999']

  - job_name: 'windows_exporter'
    static_configs:
       - targets: ['localhost:9182']
